//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BakeryStoreDBEntities : DbContext
    {
        public BakeryStoreDBEntities()
            : base("name=BakeryStoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHD> CTHDs { get; set; }
        public virtual DbSet<CTHDNhap> CTHDNhaps { get; set; }
        public virtual DbSet<DoanhThu> DoanhThus { get; set; }
        public virtual DbSet<GioHang> GioHangs { get; set; }
        public virtual DbSet<HoaDonNhap> HoaDonNhaps { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<NguyenLieu> NguyenLieux { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
    
        public virtual int sp_AnHienSP(Nullable<int> masp)
        {
            var maspParameter = masp.HasValue ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AnHienSP", maspParameter);
        }
    
        public virtual int sp_create_nguyenlieu(string ten, string donvi)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_create_nguyenlieu", tenParameter, donviParameter);
        }
    
        public virtual int sp_createhoadon(Nullable<int> id, string diachi)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_createhoadon", idParameter, diachiParameter);
        }
    
        public virtual int sp_danhGiaSP(Nullable<int> mahd, Nullable<int> masp, Nullable<int> sosao, string danhgia)
        {
            var mahdParameter = mahd.HasValue ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(int));
    
            var maspParameter = masp.HasValue ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(int));
    
            var sosaoParameter = sosao.HasValue ?
                new ObjectParameter("sosao", sosao) :
                new ObjectParameter("sosao", typeof(int));
    
            var danhgiaParameter = danhgia != null ?
                new ObjectParameter("danhgia", danhgia) :
                new ObjectParameter("danhgia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_danhGiaSP", mahdParameter, maspParameter, sosaoParameter, danhgiaParameter);
        }
    
        public virtual int sp_delete_loaisp(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_loaisp", idParameter);
        }
    
        public virtual int sp_delete_nguyenlieu(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_nguyenlieu", idParameter);
        }
    
        public virtual int sp_deletekhachhang(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_deletekhachhang", idParameter);
        }
    
        public virtual ObjectResult<sp_ds_nguyenlieu_Result> sp_ds_nguyenlieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ds_nguyenlieu_Result>("sp_ds_nguyenlieu");
        }
    
        public virtual ObjectResult<string> sp_quenmatkhau(string sdt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_quenmatkhau", sdtParameter);
        }
    
        public virtual int sp_ThemSP(string tenSP, Nullable<int> giaSP, string motaSP, string img, Nullable<int> maloai, Nullable<int> sl)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("tenSP", tenSP) :
                new ObjectParameter("tenSP", typeof(string));
    
            var giaSPParameter = giaSP.HasValue ?
                new ObjectParameter("giaSP", giaSP) :
                new ObjectParameter("giaSP", typeof(int));
    
            var motaSPParameter = motaSP != null ?
                new ObjectParameter("MotaSP", motaSP) :
                new ObjectParameter("MotaSP", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var maloaiParameter = maloai.HasValue ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(int));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemSP", tenSPParameter, giaSPParameter, motaSPParameter, imgParameter, maloaiParameter, slParameter);
        }
    
        public virtual int sp_update_nguyenlieu(string ten, Nullable<int> sl, Nullable<int> id, string donvi)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_nguyenlieu", tenParameter, slParameter, idParameter, donviParameter);
        }
    
        public virtual ObjectResult<sp_profilekhachhang_Result> sp_profilekhachhang(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_profilekhachhang_Result>("sp_profilekhachhang", idParameter);
        }
    
        public virtual int sp_updatekhachhang(Nullable<int> id, string ten, Nullable<int> gioi, string sdt, Nullable<System.DateTime> ngaysinh)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var gioiParameter = gioi.HasValue ?
                new ObjectParameter("gioi", gioi) :
                new ObjectParameter("gioi", typeof(int));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_updatekhachhang", idParameter, tenParameter, gioiParameter, sdtParameter, ngaysinhParameter);
        }
    
        public virtual ObjectResult<sp_ds_loaisp_Result> sp_ds_loaisp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ds_loaisp_Result>("sp_ds_loaisp");
        }
    
        public virtual int sp_them_loaisp(string name, string img)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_them_loaisp", nameParameter, imgParameter);
        }
    
        public virtual ObjectResult<sp_DSSP_Result> sp_DSSP(ObjectParameter totalPage, Nullable<bool> tinhtrang, string keyword, Nullable<int> maloai, Nullable<int> orderOpt, Nullable<int> page, Nullable<int> pagelength)
        {
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(bool));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var maloaiParameter = maloai.HasValue ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(int));
    
            var orderOptParameter = orderOpt.HasValue ?
                new ObjectParameter("orderOpt", orderOpt) :
                new ObjectParameter("orderOpt", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pagelengthParameter = pagelength.HasValue ?
                new ObjectParameter("pagelength", pagelength) :
                new ObjectParameter("pagelength", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DSSP_Result>("sp_DSSP", totalPage, tinhtrangParameter, keywordParameter, maloaiParameter, orderOptParameter, pageParameter, pagelengthParameter);
        }
    
        public virtual int sp_dkytaikhoan(string ten, Nullable<int> gioi, string sdt, Nullable<System.DateTime> ngaysinh, string tk, string mk)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var gioiParameter = gioi.HasValue ?
                new ObjectParameter("gioi", gioi) :
                new ObjectParameter("gioi", typeof(int));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            var mkParameter = mk != null ?
                new ObjectParameter("mk", mk) :
                new ObjectParameter("mk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dkytaikhoan", tenParameter, gioiParameter, sdtParameter, ngaysinhParameter, tkParameter, mkParameter);
        }
    
        public virtual int sp_add_gioHang(Nullable<int> maKH, Nullable<int> maSP)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("maSP", maSP) :
                new ObjectParameter("maSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_gioHang", maKHParameter, maSPParameter);
        }
    
        public virtual int sp_update_gioHang(Nullable<int> maKH, Nullable<int> maSP, Nullable<int> sl)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("maSP", maSP) :
                new ObjectParameter("maSP", typeof(int));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_gioHang", maKHParameter, maSPParameter, slParameter);
        }
    
        public virtual ObjectResult<sp_khachdangnhap_Result> sp_khachdangnhap(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_khachdangnhap_Result>("sp_khachdangnhap", userParameter, passParameter);
        }
    
        public virtual int sp_delete_gioHang(Nullable<int> maKH, Nullable<int> maSP)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("maSP", maSP) :
                new ObjectParameter("maSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_gioHang", maKHParameter, maSPParameter);
        }
    
        public virtual int sp_add_CTHD(Nullable<int> mahd, Nullable<int> masp, Nullable<int> sl)
        {
            var mahdParameter = mahd.HasValue ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(int));
    
            var maspParameter = masp.HasValue ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(int));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_CTHD", mahdParameter, maspParameter, slParameter);
        }
    
        public virtual int sp_calcTotal_gioHang(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_calcTotal_gioHang", maKHParameter);
        }
    
        public virtual int sp_thanhToan(Nullable<int> maKH, string diachi)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(int));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_thanhToan", maKHParameter, diachiParameter);
        }
    
        public virtual ObjectResult<sp_xemLichSuMua_Result> sp_xemLichSuMua(Nullable<int> makh, Nullable<int> limit)
        {
            var makhParameter = makh.HasValue ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(int));
    
            var limitParameter = limit.HasValue ?
                new ObjectParameter("limit", limit) :
                new ObjectParameter("limit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_xemLichSuMua_Result>("sp_xemLichSuMua", makhParameter, limitParameter);
        }
    
        public virtual ObjectResult<sp_ds_cthd_Result> sp_ds_cthd(Nullable<int> mahd)
        {
            var mahdParameter = mahd.HasValue ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ds_cthd_Result>("sp_ds_cthd", mahdParameter);
        }
    
        public virtual ObjectResult<sp_ds_gioHang_Result> sp_ds_gioHang(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("maKH", maKH) :
                new ObjectParameter("maKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ds_gioHang_Result>("sp_ds_gioHang", maKHParameter);
        }
    
        public virtual int sp_SuaSP(Nullable<int> maSP, string tenSP, Nullable<int> giaSP, string motaSP, string img, Nullable<double> sao, Nullable<int> luotdg, Nullable<int> maloai, Nullable<int> sl, Nullable<int> maKM, Nullable<int> tinhtrang)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("maSP", maSP) :
                new ObjectParameter("maSP", typeof(int));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("tenSP", tenSP) :
                new ObjectParameter("tenSP", typeof(string));
    
            var giaSPParameter = giaSP.HasValue ?
                new ObjectParameter("giaSP", giaSP) :
                new ObjectParameter("giaSP", typeof(int));
    
            var motaSPParameter = motaSP != null ?
                new ObjectParameter("MotaSP", motaSP) :
                new ObjectParameter("MotaSP", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var saoParameter = sao.HasValue ?
                new ObjectParameter("sao", sao) :
                new ObjectParameter("sao", typeof(double));
    
            var luotdgParameter = luotdg.HasValue ?
                new ObjectParameter("luotdg", luotdg) :
                new ObjectParameter("luotdg", typeof(int));
    
            var maloaiParameter = maloai.HasValue ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(int));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            var maKMParameter = maKM.HasValue ?
                new ObjectParameter("maKM", maKM) :
                new ObjectParameter("maKM", typeof(int));
    
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaSP", maSPParameter, tenSPParameter, giaSPParameter, motaSPParameter, imgParameter, saoParameter, luotdgParameter, maloaiParameter, slParameter, maKMParameter, tinhtrangParameter);
        }
    
        public virtual ObjectResult<sp_ChiTietSP_Result> sp_ChiTietSP(Nullable<int> masp, Nullable<int> makh)
        {
            var maspParameter = masp.HasValue ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(int));
    
            var makhParameter = makh.HasValue ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ChiTietSP_Result>("sp_ChiTietSP", maspParameter, makhParameter);
        }
    
        public virtual ObjectResult<sp_detail_loaisp_Result> sp_detail_loaisp(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detail_loaisp_Result>("sp_detail_loaisp", idParameter);
        }
    
        public virtual int sp_update_loaisp(Nullable<int> id, string name, string img)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_loaisp", idParameter, nameParameter, imgParameter);
        }
    
        public virtual ObjectResult<sp_detailhoadon_Result> sp_detailhoadon(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detailhoadon_Result>("sp_detailhoadon", idParameter);
        }
    
        public virtual int sp_update_hoadon(Nullable<int> id, Nullable<bool> ttg, string diachi)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var ttgParameter = ttg.HasValue ?
                new ObjectParameter("ttg", ttg) :
                new ObjectParameter("ttg", typeof(bool));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_hoadon", idParameter, ttgParameter, diachiParameter);
        }
    
        public virtual int sp_delete_khuyenMai(Nullable<int> maKM)
        {
            var maKMParameter = maKM.HasValue ?
                new ObjectParameter("maKM", maKM) :
                new ObjectParameter("maKM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_khuyenMai", maKMParameter);
        }
    
        public virtual ObjectResult<sp_dssp_khuyenMai_Result> sp_dssp_khuyenMai(Nullable<int> maKM)
        {
            var maKMParameter = maKM.HasValue ?
                new ObjectParameter("maKM", maKM) :
                new ObjectParameter("maKM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dssp_khuyenMai_Result>("sp_dssp_khuyenMai", maKMParameter);
        }
    
        public virtual ObjectResult<sp_dskhachhang_Result> sp_dskhachhang(ObjectParameter pageCount, Nullable<bool> isActive, string keyword, Nullable<int> page, Nullable<int> pageLength)
        {
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pageLengthParameter = pageLength.HasValue ?
                new ObjectParameter("pageLength", pageLength) :
                new ObjectParameter("pageLength", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dskhachhang_Result>("sp_dskhachhang", pageCount, isActiveParameter, keywordParameter, pageParameter, pageLengthParameter);
        }
    
        public virtual int sp_add_khuyenMai(string ten, Nullable<double> tiLe, Nullable<System.DateTime> batDau, Nullable<System.DateTime> ketThuc, string img, string mota)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var tiLeParameter = tiLe.HasValue ?
                new ObjectParameter("tiLe", tiLe) :
                new ObjectParameter("tiLe", typeof(double));
    
            var batDauParameter = batDau.HasValue ?
                new ObjectParameter("batDau", batDau) :
                new ObjectParameter("batDau", typeof(System.DateTime));
    
            var ketThucParameter = ketThuc.HasValue ?
                new ObjectParameter("ketThuc", ketThuc) :
                new ObjectParameter("ketThuc", typeof(System.DateTime));
    
            var imgParameter = img != null ?
                new ObjectParameter("img", img) :
                new ObjectParameter("img", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_khuyenMai", tenParameter, tiLeParameter, batDauParameter, ketThucParameter, imgParameter, motaParameter);
        }
    
        public virtual ObjectResult<sp_detail_khuyenMai_Result> sp_detail_khuyenMai(Nullable<int> maKM)
        {
            var maKMParameter = maKM.HasValue ?
                new ObjectParameter("maKM", maKM) :
                new ObjectParameter("maKM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detail_khuyenMai_Result>("sp_detail_khuyenMai", maKMParameter);
        }
    
        public virtual ObjectResult<sp_ds_khuyenMai_Result> sp_ds_khuyenMai(Nullable<bool> showEpxired)
        {
            var showEpxiredParameter = showEpxired.HasValue ?
                new ObjectParameter("showEpxired", showEpxired) :
                new ObjectParameter("showEpxired", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ds_khuyenMai_Result>("sp_ds_khuyenMai", showEpxiredParameter);
        }
    
        public virtual int sp_update_khuyenMai(Nullable<int> maKM, string ten, Nullable<double> tiLe, Nullable<System.DateTime> batDau, Nullable<System.DateTime> ketThuc, string mota, string pr_img)
        {
            var maKMParameter = maKM.HasValue ?
                new ObjectParameter("maKM", maKM) :
                new ObjectParameter("maKM", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var tiLeParameter = tiLe.HasValue ?
                new ObjectParameter("tiLe", tiLe) :
                new ObjectParameter("tiLe", typeof(double));
    
            var batDauParameter = batDau.HasValue ?
                new ObjectParameter("batDau", batDau) :
                new ObjectParameter("batDau", typeof(System.DateTime));
    
            var ketThucParameter = ketThuc.HasValue ?
                new ObjectParameter("ketThuc", ketThuc) :
                new ObjectParameter("ketThuc", typeof(System.DateTime));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var pr_imgParameter = pr_img != null ?
                new ObjectParameter("pr_img", pr_img) :
                new ObjectParameter("pr_img", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_khuyenMai", maKMParameter, tenParameter, tiLeParameter, batDauParameter, ketThucParameter, motaParameter, pr_imgParameter);
        }
    
        public virtual ObjectResult<sp_dshoadon_Result> sp_dshoadon(ObjectParameter totalPage, Nullable<int> page, Nullable<int> pageLimit, Nullable<int> id, Nullable<System.DateTime> ngay, Nullable<bool> tinhtrang)
        {
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pageLimitParameter = pageLimit.HasValue ?
                new ObjectParameter("pageLimit", pageLimit) :
                new ObjectParameter("pageLimit", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_dshoadon_Result>("sp_dshoadon", totalPage, pageParameter, pageLimitParameter, idParameter, ngayParameter, tinhtrangParameter);
        }
    
        public virtual ObjectResult<sp_XemDanhGiaSP_Result> sp_XemDanhGiaSP(Nullable<int> masp)
        {
            var maspParameter = masp.HasValue ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemDanhGiaSP_Result>("sp_XemDanhGiaSP", maspParameter);
        }
    
        public virtual int sp_tongHoaDon(Nullable<int> mahd)
        {
            var mahdParameter = mahd.HasValue ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tongHoaDon", mahdParameter);
        }
    
        public virtual ObjectResult<sp_popular_Result> sp_popular(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<bool> rev, Nullable<int> limit)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var revParameter = rev.HasValue ?
                new ObjectParameter("rev", rev) :
                new ObjectParameter("rev", typeof(bool));
    
            var limitParameter = limit.HasValue ?
                new ObjectParameter("limit", limit) :
                new ObjectParameter("limit", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_popular_Result>("sp_popular", fromDateParameter, toDateParameter, revParameter, limitParameter);
        }
    }
}
