//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDNhap
    {
        public int MaHDN { get; set; }
        public int MaNguyenLieu { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<int> donGia { get; set; }
    
        public virtual HoaDonNhap HoaDonNhap { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
