//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public Nullable<int> TienChi { get; set; }
        public Nullable<int> TienThu { get; set; }
        public System.DateTime Ngay { get; set; }
    }
}
